// Generated by Wrangler by running `wrangler types`

interface Env {
  LIST_KV: KVNamespace;
  MODE: string;
  LIST_DO: DurableObjectNamespace<import('./worker/index').ListDurableObject>;
  METADATA: { id: string; tag: string };
  ASSETS: Fetcher;
}
