#:schema node_modules/wrangler/config-schema.json
name = "watchlist"
main = "worker/index.ts"
compatibility_date = "2024-12-30"

[observability]
enabled = true

[placement]
mode = "smart"

[vars]
MODE = "production"

[[durable_objects.bindings]]
name = "LIST_DURABLE_OBJECT"
class_name = "ListDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ListDurableObject"]

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[build]
command = "pnpm run build"
