#:schema node_modules/wrangler/config-schema.json
name = "watchlist"
main = "worker/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_als"]

limits.cpu_ms = 500

[observability]
enabled = true

[placement]
mode = "smart"

[vars]
MODE = "production"

[version_metadata]
binding = "METADATA"

[[durable_objects.bindings]]
name = "LIST_DO"
class_name = "ListDurableObject"

[[kv_namespaces]]
id = "d66e3b0d7bb04642b3f33a1f72c9ae79"
binding = "LIST_KV"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ListDurableObject"]
