#:schema node_modules/wrangler/config-schema.json
name = "watchlist"
main = "worker/index.ts"
compatibility_date = "2024-12-30"

[observability]
enabled = true

[placement]
mode = "smart"

[vars]
MODE = "production"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]
